// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wsRXF2j5MAPa2EH2XkCbWH
// Component: FQcGunBNSB
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: LPkJNTjVmA5d/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as sty from "./PlasmicMetamaskConnect.module.css"; // plasmic-import: FQcGunBNSB/css

export const PlasmicMetamaskConnect__VariantProps = new Array();

export const PlasmicMetamaskConnect__ArgProps = new Array();

function PlasmicMetamaskConnect__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <Button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
      colors={"black"}
      rounded={"rounded"}
    >
      {"Login"}
    </Button>
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMetamaskConnect__ArgProps,
      internalVariantPropNames: PlasmicMetamaskConnect__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicMetamaskConnect__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMetamaskConnect";
  } else {
    func.displayName = `PlasmicMetamaskConnect.${nodeName}`;
  }
  return func;
}

export const PlasmicMetamaskConnect = Object.assign(
  // Top-level PlasmicMetamaskConnect renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicMetamaskConnect
    internalVariantProps: PlasmicMetamaskConnect__VariantProps,
    internalArgProps: PlasmicMetamaskConnect__ArgProps
  }
);

export default PlasmicMetamaskConnect;
/* prettier-ignore-end */
