// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wsRXF2j5MAPa2EH2XkCbWH
// Component: 3cXt94QRBKke
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k702YoelP3ze/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: wsRXF2j5MAPa2EH2XkCbWH/projectcss
import * as sty from "./PlasmicCartItem.module.css"; // plasmic-import: 3cXt94QRBKke/css
import RecycleIcon from "./icons/PlasmicIcon__Recycle"; // plasmic-import: jf9sHlWtS1Ib/icon
import Secure2Icon from "./icons/PlasmicIcon__Secure2"; // plasmic-import: xk-FIjWptLhs/icon

export const PlasmicCartItem__VariantProps = new Array();

export const PlasmicCartItem__ArgProps = new Array(
  "itemImg",
  "title",
  "productNumber",
  "size",
  "quantity"
);

function PlasmicCartItem__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return true ? (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(
        defaultcss.all,
        projectcss.all,
        projectcss.root_reset,
        sty.root
      )}
    >
      {true ? (
        <p.PlasmicImg
          data-plasmic-name={"img"}
          data-plasmic-override={overrides.img}
          alt={""}
          className={classNames(sty.img)}
          displayHeight={"auto"}
          displayMaxHeight={"none"}
          displayMaxWidth={"none"}
          displayMinHeight={"0"}
          displayMinWidth={"0"}
          displayWidth={"200px"}
          loader={"plasmic"}
          src={
            args.itemImg !== undefined
              ? args.itemImg
              : {
                  src: "https://img.plasmic.app/img-optimizer/v1/img/e70954194da0733c42049406e91000e8.png",
                  fullWidth: 450,
                  fullHeight: 450
                }
          }
        />
      ) : null}
      {true ? (
        <p.Stack
          as={"div"}
          hasGap={true}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            sty.freeBox__gYRkU
          )}
        >
          <a
            data-plasmic-name={"link"}
            data-plasmic-override={overrides.link}
            className={classNames(defaultcss.a, projectcss.a, sty.link)}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__z3FBi
              )}
            >
              {p.renderPlasmicSlot({
                defaultContents: "Some Title",
                value: args.title,
                className: classNames(sty.slotTargetTitle)
              })}
            </div>
          </a>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__eTPsg
            )}
          >
            {p.renderPlasmicSlot({
              defaultContents: "#00000",
              value: args.productNumber,
              className: classNames(sty.slotTargetProductNumber)
            })}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__hKSnn
            )}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text___3Zqa2
              )}
            >
              {"Size: "}
            </div>

            {p.renderPlasmicSlot({
              defaultContents: "11",
              value: args.size
            })}
          </div>

          <div
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox__lkCcH
            )}
          >
            <div
              className={classNames(
                defaultcss.all,
                projectcss.all,
                defaultcss.__wab_text,
                sty.text__jDHlD
              )}
            >
              {"Quantity: "}
            </div>

            {p.renderPlasmicSlot({
              defaultContents: "1",
              value: args.quantity
            })}
          </div>

          <p.Stack
            as={"div"}
            hasGap={true}
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.freeBox___2Y8TU
            )}
          >
            <RecycleIcon
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__hvt81
              )}
              role={"img"}
            />

            <Secure2Icon
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.svg__vh89E
              )}
              role={"img"}
            />
          </p.Stack>
        </p.Stack>
      ) : null}
    </div>
  ) : null;
}

const PlasmicDescendants = {
  root: ["root", "img", "link"],
  img: ["img"],
  link: ["link"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicCartItem__ArgProps,
      internalVariantPropNames: PlasmicCartItem__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicCartItem__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicCartItem";
  } else {
    func.displayName = `PlasmicCartItem.${nodeName}`;
  }
  return func;
}

export const PlasmicCartItem = Object.assign(
  // Top-level PlasmicCartItem renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    img: makeNodeComponent("img"),
    link: makeNodeComponent("link"),
    // Metadata about props expected for PlasmicCartItem
    internalVariantProps: PlasmicCartItem__VariantProps,
    internalArgProps: PlasmicCartItem__ArgProps
  }
);

export default PlasmicCartItem;
/* prettier-ignore-end */
