// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wsRXF2j5MAPa2EH2XkCbWH
// Component: j6VHmpwuKzO
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: HJQvpfJRA4yw/component
import CartItem from "../../CartItem"; // plasmic-import: 3cXt94QRBKke/component
import NftCard from "../../NftCard"; // plasmic-import: 4WAwdYQPvRJW/component
import Button from "../../Button"; // plasmic-import: LPkJNTjVmA5d/component
import Rating from "../../Rating"; // plasmic-import: 1Xj9IcyNJkl8/component
import Separator from "../../Separator"; // plasmic-import: a3Y-HjSmFyWC/component
import Footer from "../../Footer"; // plasmic-import: XC4xprCxMga4/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k702YoelP3ze/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: wsRXF2j5MAPa2EH2XkCbWH/projectcss
import * as sty from "./PlasmicOwner.module.css"; // plasmic-import: j6VHmpwuKzO/css
import Secure2Icon from "./icons/PlasmicIcon__Secure2"; // plasmic-import: xk-FIjWptLhs/icon

export const PlasmicOwner__VariantProps = new Array();

export const PlasmicOwner__ArgProps = new Array("slot3", "slot5");

function PlasmicOwner__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <p.Stack
            as={"section"}
            data-plasmic-name={"section"}
            data-plasmic-override={overrides.section}
            hasGap={true}
            className={classNames(defaultcss.all, projectcss.all, sty.section)}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__irzZn
              )}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__btFg3
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__l1Xup
                  )}
                >
                  {"You're the confirmed owner"}
                </div>

                {false ? (
                  <CartItem
                    data-plasmic-name={"cartItem"}
                    data-plasmic-override={overrides.cartItem}
                    className={classNames("__wab_instance", sty.cartItem)}
                    title={"Eternity NITRO Men's Running Shoes"}
                  />
                ) : null}

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__aazW6
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__sjbIb
                    )}
                  >
                    {
                      "We've approved you as the confirmed owner of the item and have unlocked additional features for you to engage with your physical NFT."
                    }
                  </div>

                  <div
                    data-plasmic-name={"nftContainer"}
                    data-plasmic-override={overrides.nftContainer}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.nftContainer
                    )}
                  >
                    <NftCard
                      data-plasmic-name={"nftCard"}
                      data-plasmic-override={overrides.nftCard}
                      className={classNames("__wab_instance", sty.nftCard)}
                      rating={
                        true ? (
                          <Rating
                            data-plasmic-name={"rating"}
                            data-plasmic-override={overrides.rating}
                            className={classNames("__wab_instance", sty.rating)}
                          />
                        ) : null
                      }
                      tags={
                        true ? (
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__s7EGr
                            )}
                            colors={"lightGray"}
                            size={"small"}
                          >
                            {"New"}
                          </Button>
                        ) : null
                      }
                    />
                  </div>
                </p.Stack>

                {false ? (
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__qlsUm
                    )}
                  />
                ) : null}
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__x0Hgz
                )}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__qV12
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__cDXzS
                    )}
                  >
                    {"Wallet"}
                  </div>

                  <p.Stack
                    as={"div"}
                    hasGap={true}
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__qfrV
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__iD3Kh
                      )}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox__jaKsh
                        )}
                      >
                        {p.renderPlasmicSlot({
                          defaultContents: "Balance",
                          value: args.slot5,
                          className: classNames(sty.slotTargetSlot5)
                        })}
                      </div>

                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.freeBox__wvGsQ
                        )}
                      >
                        {(
                          hasVariant(globalVariants, "screen", "mobileOnly")
                            ? true
                            : true
                        ) ? (
                          <div
                            data-plasmic-name={"balanceText"}
                            data-plasmic-override={overrides.balanceText}
                            className={classNames(
                              defaultcss.all,
                              projectcss.all,
                              defaultcss.__wab_text,
                              sty.balanceText
                            )}
                          >
                            {""}
                          </div>
                        ) : null}
                      </div>
                    </div>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator___7TVue
                      )}
                      dark={"dark"}
                    />

                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__hI4Wh
                      )}
                    >
                      {"Actions"}
                    </div>

                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__eOrff
                      )}
                    >
                      <div
                        data-plasmic-name={"columns"}
                        data-plasmic-override={overrides.columns}
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.columns
                        )}
                      >
                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.column__okT
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__fbPe3
                            )}
                            colors={"white"}
                            rounded={"rounded"}
                            size={"small"}
                          >
                            {"Sell"}
                          </Button>
                        </div>

                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.column___0FoRq
                          )}
                        >
                          <Button
                            className={classNames(
                              "__wab_instance",
                              sty.button__j5M06
                            )}
                            colors={"blue"}
                            rounded={"rounded"}
                            size={"small"}
                          >
                            {"Send"}
                          </Button>
                        </div>
                      </div>
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__ihcAl
                      )}
                      colors={"link"}
                    >
                      <div
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          defaultcss.__wab_text,
                          sty.text__wiJw
                        )}
                      >
                        {"Logout"}
                      </div>
                    </Button>

                    <Separator
                      className={classNames(
                        "__wab_instance",
                        sty.separator__pHoey
                      )}
                      dark={"dark"}
                    />

                    {false
                      ? p.renderPlasmicSlot({
                          defaultContents: true ? (
                            <Button
                              className={classNames(
                                "__wab_instance",
                                sty.button__zjFuy
                              )}
                              colors={"blue"}
                              rounded={"rounded"}
                              size={"large"}
                            >
                              <div
                                className={classNames(
                                  defaultcss.all,
                                  projectcss.all,
                                  defaultcss.__wab_text,
                                  sty.text__v3HxN
                                )}
                              >
                                {"Checkout"}
                              </div>
                            </Button>
                          ) : null,
                          value: args.slot3
                        })
                      : null}

                    <p.Stack
                      as={"div"}
                      hasGap={true}
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.freeBox__lzIs9
                      )}
                    >
                      <Secure2Icon
                        data-plasmic-name={"svg"}
                        data-plasmic-override={overrides.svg}
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg
                        )}
                        role={"img"}
                      />

                      {true ? (
                        <div
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            defaultcss.__wab_text,
                            sty.text__oiYb
                          )}
                        >
                          {"Secure"}
                        </div>
                      ) : null}
                    </p.Stack>
                  </p.Stack>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__aT9Uf
                  )}
                >
                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img___3BtoF)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"48px"}
                    loader={"plasmic"}
                    src={{
                      src: "https://site-assets.plasmic.app/beb7e86b74a29534cecf32e6c766cc8c.svg",
                      fullWidth: 210,
                      fullHeight: 150,
                      aspectRatio: 1.4
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__bPn)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"48px"}
                    loader={"plasmic"}
                    src={{
                      src: "https://site-assets.plasmic.app/3711b27f804ad7155dc1652e18a22e83.svg",
                      fullWidth: 210,
                      fullHeight: 150,
                      aspectRatio: 1.4
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__iq4J)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"48px"}
                    loader={"plasmic"}
                    src={{
                      src: "https://site-assets.plasmic.app/2eadd1488206ecaf8278c9329858061c.svg",
                      fullWidth: 210,
                      fullHeight: 150,
                      aspectRatio: 1.4
                    }}
                  />

                  <p.PlasmicImg
                    alt={""}
                    className={classNames(sty.img__oEwG8)}
                    displayHeight={"auto"}
                    displayMaxHeight={"none"}
                    displayMaxWidth={"none"}
                    displayMinHeight={"0"}
                    displayMinWidth={"0"}
                    displayWidth={"48px"}
                    loader={"plasmic"}
                    src={{
                      src: "https://site-assets.plasmic.app/189b4621c4c663bcb23e300fd33b69a6.svg",
                      fullWidth: 213,
                      fullHeight: 150,
                      aspectRatio: 1.416667
                    }}
                  />
                </p.Stack>
              </p.Stack>
            </p.Stack>

            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox___5AqPh
              )}
            >
              <p.PlasmicImg
                alt={""}
                className={classNames(sty.img__z65P6)}
                displayHeight={"32px"}
                displayMaxHeight={"none"}
                displayMaxWidth={"none"}
                displayMinHeight={"0"}
                displayMinWidth={"0"}
                displayWidth={"auto"}
                loader={"plasmic"}
                src={
                  "https://www.patagonia.com/on/demandware.static/-/Library-Sites-PatagoniaShared/default/dw4b201dc8/images/for-the-planet.png"
                }
              />

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__pyaDx
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__xlw1V
                  )}
                >
                  {"1% of your purchase will go to a grassroot organization."}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__laJli)}
                  colors={"link"}
                >
                  {"Learn more"}
                </Button>
              </p.Stack>
            </p.Stack>
          </p.Stack>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "section",
    "cartItem",
    "nftContainer",
    "nftCard",
    "rating",
    "balanceText",
    "columns",
    "svg",
    "footer"
  ],

  navBar: ["navBar"],
  section: [
    "section",
    "cartItem",
    "nftContainer",
    "nftCard",
    "rating",
    "balanceText",
    "columns",
    "svg"
  ],

  cartItem: ["cartItem"],
  nftContainer: ["nftContainer", "nftCard", "rating"],
  nftCard: ["nftCard", "rating"],
  rating: ["rating"],
  balanceText: ["balanceText"],
  columns: ["columns"],
  svg: ["svg"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicOwner__ArgProps,
      internalVariantPropNames: PlasmicOwner__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicOwner__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicOwner";
  } else {
    func.displayName = `PlasmicOwner.${nodeName}`;
  }
  return func;
}

export const PlasmicOwner = Object.assign(
  // Top-level PlasmicOwner renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    section: makeNodeComponent("section"),
    cartItem: makeNodeComponent("cartItem"),
    nftContainer: makeNodeComponent("nftContainer"),
    nftCard: makeNodeComponent("nftCard"),
    rating: makeNodeComponent("rating"),
    balanceText: makeNodeComponent("balanceText"),
    columns: makeNodeComponent("columns"),
    svg: makeNodeComponent("svg"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicOwner
    internalVariantProps: PlasmicOwner__VariantProps,
    internalArgProps: PlasmicOwner__ArgProps
  }
);

export default PlasmicOwner;
/* prettier-ignore-end */
