// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wsRXF2j5MAPa2EH2XkCbWH
// Component: -FouedilvpF8
import * as React from "react";
import * as p from "@plasmicapp/react-web";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";
import NavBar from "../../NavBar"; // plasmic-import: HJQvpfJRA4yw/component
import Button from "../../Button"; // plasmic-import: LPkJNTjVmA5d/component
import NftCard from "../../NftCard"; // plasmic-import: 4WAwdYQPvRJW/component
import Rating from "../../Rating"; // plasmic-import: 1Xj9IcyNJkl8/component
import EmojiValueProps from "../../EmojiValueProps"; // plasmic-import: hziPCigE40Ol/component
import Value from "../../Value"; // plasmic-import: u3HUpc_KJfUr/component
import Footer from "../../Footer"; // plasmic-import: XC4xprCxMga4/component
import { useScreenVariants } from "./PlasmicGlobalVariant__Screen"; // plasmic-import: k702YoelP3ze/globalVariant
import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_ecommerce_starter.module.css"; // plasmic-import: wsRXF2j5MAPa2EH2XkCbWH/projectcss
import * as sty from "./PlasmicHomepage.module.css"; // plasmic-import: -FouedilvpF8/css
import RightArrowIcon from "./icons/PlasmicIcon__RightArrow"; // plasmic-import: sth0rOpjGBUT/icon
import PlaneIcon from "./icons/PlasmicIcon__Plane"; // plasmic-import: dACW4CNxAiAj/icon
import DocumentIcon from "./icons/PlasmicIcon__Document"; // plasmic-import: Hc5XEg5ZBHkC/icon
import LockIcon from "./icons/PlasmicIcon__Lock"; // plasmic-import: bSjUcOohvTSQ/icon
import SpeakerphoneIcon from "./icons/PlasmicIcon__Speakerphone"; // plasmic-import: o8FsI2Crd5Vn/icon
import MedalIcon from "./icons/PlasmicIcon__Medal"; // plasmic-import: TexMxJ0_e7e0/icon
import LeafIcon from "./icons/PlasmicIcon__Leaf"; // plasmic-import: SrJCky5IumiA/icon
import ShoeIcon from "./icons/PlasmicIcon__Shoe"; // plasmic-import: HmqbLf-wN8-Q/icon
import PeaceIcon from "./icons/PlasmicIcon__Peace"; // plasmic-import: dDDsqr_IzqaC/icon

export const PlasmicHomepage__VariantProps = new Array();

export const PlasmicHomepage__ArgProps = new Array("container42");

function PlasmicHomepage__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  const globalVariants = ensureGlobalVariants({
    screen: useScreenVariants()
  });

  return (
    <React.Fragment>
      <div className={defaultcss.plasmic_page_wrapper}>
        <div
          data-plasmic-name={"root"}
          data-plasmic-override={overrides.root}
          data-plasmic-root={true}
          data-plasmic-for-node={forNode}
          className={classNames(
            defaultcss.all,
            projectcss.all,
            projectcss.root_reset,
            sty.root
          )}
        >
          <NavBar
            data-plasmic-name={"navBar"}
            data-plasmic-override={overrides.navBar}
            className={classNames("__wab_instance", sty.navBar)}
          />

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section__omiZn
            )}
          >
            <p.PlasmicImg
              data-plasmic-name={"img"}
              data-plasmic-override={overrides.img}
              alt={""}
              className={classNames(sty.img)}
              displayHeight={"auto"}
              displayMaxHeight={"none"}
              displayMaxWidth={"none"}
              displayMinHeight={"0"}
              displayMinWidth={"0"}
              displayWidth={"100%"}
              loader={"plasmic"}
              src={{
                src: "https://img.plasmic.app/img-optimizer/v1/img/e4ef9956583173c47118d7959c68e57b.png",
                fullWidth: 2048,
                fullHeight: 1415
              }}
            />

            <p.Stack
              as={"div"}
              data-plasmic-name={"container3"}
              data-plasmic-override={overrides.container3}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container3
              )}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__pRmKi
                )}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox___3Q9Ed
                  )}
                >
                  <h1
                    data-plasmic-name={"h1"}
                    data-plasmic-override={overrides.h1}
                    className={classNames(
                      defaultcss.h1,
                      projectcss.h1,
                      defaultcss.__wab_text,
                      sty.h1
                    )}
                  >
                    {"unlimitid"}
                  </h1>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__tdVZb
                    )}
                  >
                    {
                      "Provably authentic physical fashion and art, digitally owned and provably yours. The future of genuine goods."
                    }
                  </div>
                </p.Stack>

                <Button
                  className={classNames("__wab_instance", sty.button___0GztJ)}
                  colors={"black"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__qjOcf
                      )}
                      role={"img"}
                    />
                  }
                  link={"/category"}
                  rounded={"rounded"}
                  showEndIcon={"showEndIcon"}
                  size={"large"}
                >
                  {"Shop"}
                </Button>
              </p.Stack>
            </p.Stack>
          </section>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section__hGjm
            )}
          >
            <div
              data-plasmic-name={"container4"}
              data-plasmic-override={overrides.container4}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container4
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__guyX
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__e6PmH
                  )}
                >
                  {"Featured"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__z1P0N)}
                  colors={"link"}
                  endIcon={
                    <RightArrowIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__uOaVg
                      )}
                      role={"img"}
                    />
                  }
                  link={"/category"}
                  showEndIcon={"showEndIcon"}
                >
                  {"See more"}
                </Button>
              </div>
            </div>

            <p.Stack
              as={"div"}
              data-plasmic-name={"container"}
              data-plasmic-override={overrides.container}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container
              )}
            >
              <NftCard
                className={classNames("__wab_instance", sty.nftCard__cWri)}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/aca490781ed5cdb4bc673dfbf6446fb4.png",
                  fullWidth: 840,
                  fullHeight: 840
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__j5Uyo)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />

              <NftCard
                className={classNames("__wab_instance", sty.nftCard___8E0V)}
                dollars={"79"}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/9684c86e748e82236bfc836da1bc4ab9.png",
                  fullWidth: 864,
                  fullHeight: 1080
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__rTwX8)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />

              <NftCard
                className={classNames("__wab_instance", sty.nftCard__mXh)}
                dollars={"64"}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/d1a314023737aac5a73fede7f1ef1e00.png",
                  fullWidth: 840,
                  fullHeight: 840
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__dVmsZ)}
                    rating={"two"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />

              <NftCard
                className={classNames("__wab_instance", sty.nftCard__ds2AE)}
                dollars={"99"}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/946b8531b58062ba8a6a94192775b40a.png",
                  fullWidth: 864,
                  fullHeight: 1080
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__cvRGg)}
                    rating={"four"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />

              <NftCard
                className={classNames("__wab_instance", sty.nftCard__xbXja)}
                dollars={"79"}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/23e46f1954faac60c6dd6d1923dab092.png",
                  fullWidth: 840,
                  fullHeight: 840
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__iMGc)}
                    rating={"five"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />

              <NftCard
                className={classNames("__wab_instance", sty.nftCard__mb2Of)}
                dollars={"65"}
                img={{
                  src: "https://img.plasmic.app/img-optimizer/v1/img/222d696f36d9aa3ef5fda6c5a888448e.png",
                  fullWidth: 864,
                  fullHeight: 1080
                }}
                link={"/item"}
                rating={
                  <Rating
                    className={classNames("__wab_instance", sty.rating__jddNi)}
                    rating={"threeHalf"}
                  />
                }
                tags={
                  <Button colors={"lightGray"} size={"small"}>
                    {"New"}
                  </Button>
                }
              />
            </p.Stack>
          </section>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section___5Abp1
            )}
          >
            <p.Stack
              as={"div"}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.freeBox__kMl4B
              )}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__iUYuc
                )}
              >
                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox__jb09Q
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__npxIo
                    )}
                  >
                    {"Our best shoe sale of the year"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__g30U4
                    )}
                  >
                    {
                      "Signature style. Unsurpassed quality and comfort. Now’s the perfect time to save on iconic shoes."
                    }
                  </div>
                </p.Stack>

                <p.Stack
                  as={"div"}
                  hasGap={true}
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    sty.freeBox___2MyOk
                  )}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__z0GO6
                    )}
                  >
                    <span
                      className={"plasmic_default__all plasmic_default__span"}
                    >
                      <React.Fragment>{"3 "}</React.Fragment>
                      <span
                        className={"plasmic_default__all plasmic_default__span"}
                        style={{ fontStyle: "italic" }}
                      >
                        {"for"}
                      </span>
                      <React.Fragment>{" $169"}</React.Fragment>
                    </span>
                  </div>

                  <Button
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg___1YiMr
                        )}
                        role={"img"}
                      />
                    }
                    link={"/category"}
                    rounded={"rounded"}
                    showEndIcon={"showEndIcon"}
                    size={"large"}
                  >
                    {"Shop sale"}
                  </Button>
                </p.Stack>
              </p.Stack>
            </p.Stack>
          </section>

          <EmojiValueProps
            data-plasmic-name={"emojiValueProps"}
            data-plasmic-override={overrides.emojiValueProps}
            className={classNames("__wab_instance", sty.emojiValueProps)}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"columns"}
              data-plasmic-override={overrides.columns}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.columns
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__vd66W
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xbV8W
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__lTkWo
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___1NaVw)}
                  icon={
                    <PlaneIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__suIvi
                      )}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__kiJsz
                    )}
                  >
                    {"Worldwide shipping"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__gYxfU
                    )}
                  >
                    {"Special financing and earn rewards."}
                  </div>
                </Value>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__li3Nz
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__mw875
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__ebkrX
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__ipEm4)}
                  icon={
                    <DocumentIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__jUfe
                      )}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__bEddN
                    )}
                  >
                    {"30-day guarantee"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__igfjd
                    )}
                  >
                    {"Free return policy."}
                  </div>
                </Value>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__uk2Go
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__xeW74
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__y6I64
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__iPa1B)}
                  icon={
                    <LockIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg___8AEL
                      )}
                      role={"img"}
                    />
                  }
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__uv2T
                    )}
                  >
                    {"Secured payments"}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__pfArt
                    )}
                  >
                    {"We accept major credit cards."}
                  </div>
                </Value>
              </div>
            </p.Stack>
          </EmojiValueProps>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section__vL1EN
            )}
          >
            <div
              data-plasmic-name={"container42"}
              data-plasmic-override={overrides.container42}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container42
              )}
            >
              {p.renderPlasmicSlot({
                defaultContents: (
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.freeBox__vQjOy
                    )}
                  >
                    <div
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        defaultcss.__wab_text,
                        sty.text__tj8Y
                      )}
                    >
                      {"Just added"}
                    </div>

                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__h0M8S
                      )}
                      colors={"link"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__iudZ
                          )}
                          role={"img"}
                        />
                      }
                      link={"/category"}
                      showEndIcon={"showEndIcon"}
                    >
                      {"See more"}
                    </Button>
                  </div>
                ),

                value: args.container42
              })}
            </div>

            <div
              data-plasmic-name={"container5"}
              data-plasmic-override={overrides.container5}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container5
              )}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__kYgd
                )}
              >
                <NftCard
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/aca490781ed5cdb4bc673dfbf6446fb4.png",
                    fullWidth: 840,
                    fullHeight: 840
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__jqpcu)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/9684c86e748e82236bfc836da1bc4ab9.png",
                    fullWidth: 864,
                    fullHeight: 1080
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__v88Pl)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/d1a314023737aac5a73fede7f1ef1e00.png",
                    fullWidth: 840,
                    fullHeight: 840
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__g63UI)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/946b8531b58062ba8a6a94192775b40a.png",
                    fullWidth: 864,
                    fullHeight: 1080
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__cWhlg)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/23e46f1954faac60c6dd6d1923dab092.png",
                    fullWidth: 840,
                    fullHeight: 840
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__ow4Zn)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/222d696f36d9aa3ef5fda6c5a888448e.png",
                    fullWidth: 864,
                    fullHeight: 1080
                  }}
                  link={"/item"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </div>
          </section>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section__wycRx
            )}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container6"}
              data-plasmic-override={overrides.container6}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container6
              )}
            >
              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__w0InW
                )}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__vr76P
                  )}
                >
                  {"Categories"}
                </div>

                <Button
                  className={classNames("__wab_instance", sty.button__bmaZ7)}
                  states={"active"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__dOh4O
                    )}
                  >
                    {"All"}
                  </div>
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__afHo)}
                >
                  {"New"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__xz05L)}
                >
                  {"Womens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__yLrOh)}
                >
                  {"Mens"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__lNvkE)}
                >
                  {"Kids"}
                </Button>

                <Button
                  className={classNames("__wab_instance", sty.button__zwkiX)}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__oA4Ux
                    )}
                  >
                    {"On sale"}
                  </div>
                </Button>
              </p.Stack>

              <p.Stack
                as={"div"}
                hasGap={true}
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.freeBox__pyrlB
                )}
              >
                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__nxX51)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/27587210711d41af77703fb12e0df8f4.png",
                    fullWidth: 864,
                    fullHeight: 1080
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__eiAxZ)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/e179c29f390de79c3ec3aada27732e64.png",
                    fullWidth: 840,
                    fullHeight: 840
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard___1BAts)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/56b9e305cfe5297b4d9b9233ed9c3083.png",
                    fullWidth: 320,
                    fullHeight: 320
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__sWpAy)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/e5ff5d24d4147571ef0610520f74eaf0.png",
                    fullWidth: 2000,
                    fullHeight: 2000
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard___4LdGb)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/efddec03027d36e0a52dfc61e3c4ad2b.png",
                    fullWidth: 1024,
                    fullHeight: 768
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__eAwVd)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/9fa4193291fa88aaefc33131274c8ab4.png",
                    fullWidth: 964,
                    fullHeight: 898
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__awZjf)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/0d068a5f1b6662e7652eebef8b3df423.png",
                    fullWidth: 864,
                    fullHeight: 1080
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__j838J)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/567e7aed36548b16eec4a6d1454ad219.png",
                    fullWidth: 1024,
                    fullHeight: 768
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__ltUO)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/051a538116736eadbf1efb3622835451.png",
                    fullWidth: 964,
                    fullHeight: 898
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__qaIis)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/4b665a5b5c55a34b1f07ba74bc2500ed.png",
                    fullWidth: 766,
                    fullHeight: 766
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard__f2Xn)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/3147e2e08b361785b8dd3811f4641a6e.png",
                    fullWidth: 2000,
                    fullHeight: 2000
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />

                <NftCard
                  className={classNames("__wab_instance", sty.nftCard___52Ywm)}
                  img={{
                    src: "https://img.plasmic.app/img-optimizer/v1/img/befe1df81efc9a28d3235362e92f0fa8.png",
                    fullWidth: 840,
                    fullHeight: 840
                  }}
                  link={"/item"}
                  small={"small"}
                  tags={
                    <Button colors={"lightGray"} size={"small"}>
                      {"New"}
                    </Button>
                  }
                />
              </p.Stack>
            </p.Stack>
          </section>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section___7ZcA3
            )}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container434"}
              data-plasmic-override={overrides.container434}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container434
              )}
            >
              <Value
                center={"center"}
                children2={
                  <Button
                    className={classNames("__wab_instance", sty.button__akG4L)}
                    colors={"black"}
                    endIcon={
                      <RightArrowIcon
                        className={classNames(
                          defaultcss.all,
                          projectcss.all,
                          sty.svg__u8TzA
                        )}
                        role={"img"}
                      />
                    }
                    rounded={"rounded"}
                    showEndIcon={"showEndIcon"}
                  >
                    {"Read our letter"}
                  </Button>
                }
                className={classNames("__wab_instance", sty.value__rGljP)}
                icon={
                  <SpeakerphoneIcon
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      sty.svg___4Sk4L
                    )}
                    role={"img"}
                  />
                }
                topBottom={"topBottom"}
                withButton={"withButton"}
              >
                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__ybv9L
                  )}
                >
                  {"Our goals"}
                </div>

                <div
                  className={classNames(
                    defaultcss.all,
                    projectcss.all,
                    defaultcss.__wab_text,
                    sty.text__mYbtL
                  )}
                >
                  {"We’re learning how to become a new kind of company."}
                </div>
              </Value>
            </p.Stack>
          </section>

          <section
            className={classNames(
              defaultcss.all,
              projectcss.all,
              sty.section__zjCeZ
            )}
          >
            <p.Stack
              as={"div"}
              data-plasmic-name={"container433"}
              data-plasmic-override={overrides.container433}
              hasGap={true}
              className={classNames(
                defaultcss.all,
                projectcss.all,
                sty.container433
              )}
            >
              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__eZCv8
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__eqoCw
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__rTQp
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__uu8Aj)}
                  icon={
                    <MedalIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__q8Pbe
                      )}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__eI1Ch
                    )}
                  >
                    {"We guarantee everything we sell."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__stGgx
                    )}
                  >
                    {
                      "Ad fringilla ut nisi in hendrerit malesuada nascetur a in ridiculus."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__o4Njp)}
                    colors={"link"}
                  >
                    {"View guarantee"}
                  </Button>
                </Value>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__fO9Hq
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__bswnk
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__vump2
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value___8T0Jw)}
                  icon={
                    <LeafIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__joK1E
                      )}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__spm9R
                    )}
                  >
                    {"Know how your shoes are made."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text___9O4CG
                    )}
                  >
                    {
                      "Parturient blandit viverra blandit sem suspendisse himenaeos."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button___4X9N)}
                    colors={"link"}
                  />
                </Value>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__bavvi
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button__j8Ham
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__k2XzH
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__wYdxu)}
                  icon={
                    <ShoeIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__ljkvm
                      )}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__mPim0
                    )}
                  >
                    {"Keep your shoes in play."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__afKk3
                    )}
                  >
                    {
                      "Adipiscing ornare dui tellus nam nibh cum a torquent maecenas."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__tzOPg)}
                    colors={"link"}
                  />
                </Value>
              </div>

              <div
                className={classNames(
                  defaultcss.all,
                  projectcss.all,
                  sty.column__zorAr
                )}
              >
                <Value
                  children2={
                    <Button
                      className={classNames(
                        "__wab_instance",
                        sty.button___3MrhE
                      )}
                      colors={"black"}
                      endIcon={
                        <RightArrowIcon
                          className={classNames(
                            defaultcss.all,
                            projectcss.all,
                            sty.svg__g2TRh
                          )}
                          role={"img"}
                        />
                      }
                      rounded={"rounded"}
                      size={"large"}
                    >
                      {"Read our letter"}
                    </Button>
                  }
                  className={classNames("__wab_instance", sty.value__rCiGs)}
                  icon={
                    <PeaceIcon
                      className={classNames(
                        defaultcss.all,
                        projectcss.all,
                        sty.svg__n1U8
                      )}
                      role={"img"}
                    />
                  }
                  topBottom={"topBottom"}
                >
                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__j30Nb
                    )}
                  >
                    {"We give back for every sale."}
                  </div>

                  <div
                    className={classNames(
                      defaultcss.all,
                      projectcss.all,
                      defaultcss.__wab_text,
                      sty.text__xcubt
                    )}
                  >
                    {
                      "Parturient vestibulum ut a dui parturient habitant netus integer ipsum."
                    }
                  </div>

                  <Button
                    className={classNames("__wab_instance", sty.button__rF0Mz)}
                    colors={"link"}
                  />
                </Value>
              </div>
            </p.Stack>
          </section>

          <Footer
            data-plasmic-name={"footer"}
            data-plasmic-override={overrides.footer}
            className={classNames("__wab_instance", sty.footer)}
          />
        </div>
      </div>
    </React.Fragment>
  );
}

const PlasmicDescendants = {
  root: [
    "root",
    "navBar",
    "img",
    "container3",
    "h1",
    "container4",
    "container",
    "emojiValueProps",
    "columns",
    "container42",
    "container5",
    "container6",
    "container434",
    "container433",
    "footer"
  ],

  navBar: ["navBar"],
  img: ["img"],
  container3: ["container3", "h1"],
  h1: ["h1"],
  container4: ["container4"],
  container: ["container"],
  emojiValueProps: ["emojiValueProps", "columns"],
  columns: ["columns"],
  container42: ["container42"],
  container5: ["container5"],
  container6: ["container6"],
  container434: ["container434"],
  container433: ["container433"],
  footer: ["footer"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicHomepage__ArgProps,
      internalVariantPropNames: PlasmicHomepage__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicHomepage__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicHomepage";
  } else {
    func.displayName = `PlasmicHomepage.${nodeName}`;
  }
  return func;
}

export const PlasmicHomepage = Object.assign(
  // Top-level PlasmicHomepage renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    navBar: makeNodeComponent("navBar"),
    img: makeNodeComponent("img"),
    container3: makeNodeComponent("container3"),
    h1: makeNodeComponent("h1"),
    container4: makeNodeComponent("container4"),
    container: makeNodeComponent("container"),
    emojiValueProps: makeNodeComponent("emojiValueProps"),
    columns: makeNodeComponent("columns"),
    container42: makeNodeComponent("container42"),
    container5: makeNodeComponent("container5"),
    container6: makeNodeComponent("container6"),
    container434: makeNodeComponent("container434"),
    container433: makeNodeComponent("container433"),
    footer: makeNodeComponent("footer"),
    // Metadata about props expected for PlasmicHomepage
    internalVariantProps: PlasmicHomepage__VariantProps,
    internalArgProps: PlasmicHomepage__ArgProps
  }
);

export default PlasmicHomepage;
/* prettier-ignore-end */
