// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: wsRXF2j5MAPa2EH2XkCbWH
// Component: YMGP7swsZj
import * as React from "react";
import {
  classNames,
  createPlasmicElementProxy,
  deriveRenderOpts
} from "@plasmicapp/react-web";
import Button from "../../Button"; // plasmic-import: LPkJNTjVmA5d/component
import "@plasmicapp/react-web/lib/plasmic.css";
import * as sty from "./PlasmicX.module.css"; // plasmic-import: YMGP7swsZj/css

export const PlasmicX__VariantProps = new Array();

export const PlasmicX__ArgProps = new Array();

function PlasmicX__RenderFunc(props) {
  const { variants, args, overrides, forNode, dataFetches } = props;
  return (
    <Button
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames("__wab_instance", sty.root)}
    />
  );
}

const PlasmicDescendants = {
  root: ["root"]
};

function makeNodeComponent(nodeName) {
  const func = function (props) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicX__ArgProps,
      internalVariantPropNames: PlasmicX__VariantProps
    });

    const { dataFetches } = props;
    return PlasmicX__RenderFunc({
      variants,
      args,
      overrides,
      dataFetches,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicX";
  } else {
    func.displayName = `PlasmicX.${nodeName}`;
  }
  return func;
}

export const PlasmicX = Object.assign(
  // Top-level PlasmicX renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    // Metadata about props expected for PlasmicX
    internalVariantProps: PlasmicX__VariantProps,
    internalArgProps: PlasmicX__ArgProps
  }
);

export default PlasmicX;
/* prettier-ignore-end */
