// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicItem } from "./plasmic/ecommerce_starter/PlasmicItem";
import { useNFTBalance } from "hooks/useNFTBalance";
//import { useCallback, useEffect, useRef, useState } from "react";

function Item_(props, ref) {
    
      const queryString = require('query-string');
      //get url and split out attribute, which will be NFT contract address
      const windowUrl = window.location.search;
      const params = queryString.parse(windowUrl);

      const { NFTBalance } = useNFTBalance();
      const [Nft, setNft] = useState(null);
      console.log(NFTBalance, params);

      useEffect(() => {
      setNft(NFTBalance.filter(function(data){return data.token_id == params.id})[0])      
      console.log(Nft, "the nft");
      },[])

  return <PlasmicItem root={{ ref }} {...props} 
  nftNamePage={{
    //children: nft[0].name
    }}
  nftDescPage={{
    //children: nft[0].description
    }}
  nftImagePage={{
    //children: nft[0].image
    }}


  />;
}

const Item = React.forwardRef(Item_);

export default Item;