// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicMetamaskConnect } from "./plasmic/ecommerce_starter/PlasmicMetamaskConnect";

function MetamaskConnect(props) {

  return <PlasmicMetamaskConnect {...props} />;

}

export default MetamaskConnect;
