// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicNavBar } from "./plasmic/ecommerce_starter/PlasmicNavBar";
import { useMoralis } from "react-moralis";

function NavBar_(props, ref) {
  
  const { authenticate, isAuthenticated, user, logout } = useMoralis();

  if (!isAuthenticated) {
    console.log("not authenticated", user);
        return <PlasmicNavBar root={{ ref }} {...props} 
          metamaskConnect={{
              onClick: () => authenticate(),
              children: "Login"
          }}
        />;
  }else{
    console.log("authenticated", user);
        return <PlasmicNavBar root={{ ref }} {...props} 
          metamaskConnect={{
              onClick: () => logout(),
              children: "Logout"
          }}
        />;
      }
}

const NavBar = React.forwardRef(NavBar_);

export default NavBar;
