// This is a skeleton starter React component generated by Plasmic.
// This file is owned by you, feel free to edit as you see fit.
import * as React from "react";
import { PlasmicWallet } from "./plasmic/ecommerce_starter/PlasmicWallet";
import NativeBalance from "components/NativeBalance";
import NFTBalance from "components/NFTBalance";
import { useMoralis } from "react-moralis";

function Wallet_(props, ref) {
  
  const { logout } = useMoralis();
  
  return (<PlasmicWallet root={{ ref }} {...props} 
  balanceText={{
    children: <NativeBalance />
  }}
  nftContainer={{
    children: <NFTBalance />
  }}
  walletLogout={{
    onClick: () => logout()
  }}
  />)
}

const Wallet = React.forwardRef(Wallet_);

export default Wallet;
